namespace Funcionarios.Models.Enums
{
    public enum TSql
    {
        CADASTRAR_FUNCIONARIO,
        LISTAR_FUNCIONARIO,
        ATUALIZAR_FUNCIONARIO,
        PESQUISAR_FUNCIONARIO,
        EXCLUIR_FUNCIONARIO,
        CADASTRAR_FUNCIONARIO2,
        ATUALIZAR_FUNCIONARIO2,
        EXCLUIR_ENDERECO
    }
}
